# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'E:\svn\SrneUpperComputer\ui\dc_layout.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1181, 552)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.tab)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setContentsMargins(5, 5, 5, 5)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox = QtWidgets.QGroupBox(self.tab)
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.groupBox)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.dc_software_ver = QtWidgets.QLineEdit(self.groupBox)
        self.dc_software_ver.setObjectName("dc_software_ver")
        self.gridLayout.addWidget(self.dc_software_ver, 1, 3, 1, 1)
        self.dc_can_ver = QtWidgets.QLineEdit(self.groupBox)
        self.dc_can_ver.setObjectName("dc_can_ver")
        self.gridLayout.addWidget(self.dc_can_ver, 2, 5, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.groupBox)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 1, 2, 1, 1)
        self.dc_product_spec = QtWidgets.QLineEdit(self.groupBox)
        self.dc_product_spec.setObjectName("dc_product_spec")
        self.gridLayout.addWidget(self.dc_product_spec, 1, 1, 1, 1)
        self.dc_dev_name = QtWidgets.QLineEdit(self.groupBox)
        self.dc_dev_name.setObjectName("dc_dev_name")
        self.gridLayout.addWidget(self.dc_dev_name, 3, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 0, 4, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 2, 1, 1)
        self.dc_product_type = QtWidgets.QLineEdit(self.groupBox)
        self.dc_product_type.setObjectName("dc_product_type")
        self.gridLayout.addWidget(self.dc_product_type, 0, 5, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.groupBox)
        self.label_10.setObjectName("label_10")
        self.gridLayout.addWidget(self.label_10, 3, 0, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.groupBox)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 1, 4, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 1, 0, 1, 1)
        self.dc_product_sn = QtWidgets.QLineEdit(self.groupBox)
        self.dc_product_sn.setObjectName("dc_product_sn")
        self.gridLayout.addWidget(self.dc_product_sn, 2, 1, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.groupBox)
        self.label_9.setObjectName("label_9")
        self.gridLayout.addWidget(self.label_9, 2, 4, 1, 1)
        self.dc_hardware_ver = QtWidgets.QLineEdit(self.groupBox)
        self.dc_hardware_ver.setObjectName("dc_hardware_ver")
        self.gridLayout.addWidget(self.dc_hardware_ver, 1, 5, 1, 1)
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.dc_dev_addr = QtWidgets.QLineEdit(self.groupBox)
        self.dc_dev_addr.setObjectName("dc_dev_addr")
        self.gridLayout.addWidget(self.dc_dev_addr, 2, 3, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.groupBox)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 2, 2, 1, 1)
        self.dc_rate_charg_cur = QtWidgets.QLineEdit(self.groupBox)
        self.dc_rate_charg_cur.setObjectName("dc_rate_charg_cur")
        self.gridLayout.addWidget(self.dc_rate_charg_cur, 0, 3, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.groupBox)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 2, 0, 1, 1)
        self.dc_sys_vol = QtWidgets.QLineEdit(self.groupBox)
        self.dc_sys_vol.setObjectName("dc_sys_vol")
        self.gridLayout.addWidget(self.dc_sys_vol, 0, 1, 1, 1)
        self.horizontalLayout_4.addLayout(self.gridLayout)
        self.verticalLayout.addWidget(self.groupBox)
        self.groupBox_2 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_2.setObjectName("groupBox_2")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.groupBox_2)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_16 = QtWidgets.QLabel(self.groupBox_2)
        self.label_16.setObjectName("label_16")
        self.gridLayout_2.addWidget(self.label_16, 1, 4, 1, 1)
        self.label_23 = QtWidgets.QLabel(self.groupBox_2)
        self.label_23.setObjectName("label_23")
        self.gridLayout_2.addWidget(self.label_23, 4, 0, 1, 1)
        self.dc_input_vol = QtWidgets.QLineEdit(self.groupBox_2)
        self.dc_input_vol.setObjectName("dc_input_vol")
        self.gridLayout_2.addWidget(self.dc_input_vol, 1, 3, 1, 1)
        self.label_28 = QtWidgets.QLabel(self.groupBox_2)
        self.label_28.setObjectName("label_28")
        self.gridLayout_2.addWidget(self.label_28, 5, 4, 1, 1)
        self.label_18 = QtWidgets.QLabel(self.groupBox_2)
        self.label_18.setObjectName("label_18")
        self.gridLayout_2.addWidget(self.label_18, 2, 2, 1, 1)
        self.label_17 = QtWidgets.QLabel(self.groupBox_2)
        self.label_17.setObjectName("label_17")
        self.gridLayout_2.addWidget(self.label_17, 2, 0, 1, 1)
        self.dc_chg_state = QtWidgets.QLineEdit(self.groupBox_2)
        self.dc_chg_state.setObjectName("dc_chg_state")
        self.gridLayout_2.addWidget(self.dc_chg_state, 5, 1, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.groupBox_2)
        self.label_12.setObjectName("label_12")
        self.gridLayout_2.addWidget(self.label_12, 0, 2, 1, 1)
        self.label_25 = QtWidgets.QLabel(self.groupBox_2)
        self.label_25.setObjectName("label_25")
        self.gridLayout_2.addWidget(self.label_25, 4, 4, 1, 1)
        self.dc_today_chgAH = QtWidgets.QLineEdit(self.groupBox_2)
        self.dc_today_chgAH.setObjectName("dc_today_chgAH")
        self.gridLayout_2.addWidget(self.dc_today_chgAH, 3, 1, 1, 1)
        self.dc_open_max_chg_curr = QtWidgets.QLineEdit(self.groupBox_2)
        self.dc_open_max_chg_curr.setObjectName("dc_open_max_chg_curr")
        self.gridLayout_2.addWidget(self.dc_open_max_chg_curr, 2, 5, 1, 1)
        self.dc_mos_tmp = QtWidgets.QLineEdit(self.groupBox_2)
        self.dc_mos_tmp.setObjectName("dc_mos_tmp")
        self.gridLayout_2.addWidget(self.dc_mos_tmp, 5, 3, 1, 1)
        self.label_20 = QtWidgets.QLabel(self.groupBox_2)
        self.label_20.setObjectName("label_20")
        self.gridLayout_2.addWidget(self.label_20, 3, 0, 1, 1)
        self.dc_radiator = QtWidgets.QLineEdit(self.groupBox_2)
        self.dc_radiator.setObjectName("dc_radiator")
        self.gridLayout_2.addWidget(self.dc_radiator, 5, 5, 1, 1)
        self.dc_today_genera = QtWidgets.QLineEdit(self.groupBox_2)
        self.dc_today_genera.setObjectName("dc_today_genera")
        self.gridLayout_2.addWidget(self.dc_today_genera, 3, 3, 1, 1)
        self.dc_charge_power = QtWidgets.QLineEdit(self.groupBox_2)
        self.dc_charge_power.setObjectName("dc_charge_power")
        self.gridLayout_2.addWidget(self.dc_charge_power, 1, 5, 1, 1)
        self.dc_open_min_vol = QtWidgets.QLineEdit(self.groupBox_2)
        self.dc_open_min_vol.setObjectName("dc_open_min_vol")
        self.gridLayout_2.addWidget(self.dc_open_min_vol, 2, 1, 1, 1)
        self.dc_total_bat_chgAH = QtWidgets.QLineEdit(self.groupBox_2)
        self.dc_total_bat_chgAH.setObjectName("dc_total_bat_chgAH")
        self.gridLayout_2.addWidget(self.dc_total_bat_chgAH, 4, 3, 1, 1)
        self.dc_bat_tmp = QtWidgets.QLineEdit(self.groupBox_2)
        self.dc_bat_tmp.setObjectName("dc_bat_tmp")
        self.gridLayout_2.addWidget(self.dc_bat_tmp, 1, 1, 1, 1)
        self.dc_open_max_vol = QtWidgets.QLineEdit(self.groupBox_2)
        self.dc_open_max_vol.setObjectName("dc_open_max_vol")
        self.gridLayout_2.addWidget(self.dc_open_max_vol, 2, 3, 1, 1)
        self.dc_dev_tmp = QtWidgets.QLineEdit(self.groupBox_2)
        self.dc_dev_tmp.setObjectName("dc_dev_tmp")
        self.gridLayout_2.addWidget(self.dc_dev_tmp, 0, 5, 1, 1)
        self.label_22 = QtWidgets.QLabel(self.groupBox_2)
        self.label_22.setObjectName("label_22")
        self.gridLayout_2.addWidget(self.label_22, 3, 4, 1, 1)
        self.dc_bat_vol = QtWidgets.QLineEdit(self.groupBox_2)
        self.dc_bat_vol.setObjectName("dc_bat_vol")
        self.gridLayout_2.addWidget(self.dc_bat_vol, 0, 1, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.groupBox_2)
        self.label_13.setObjectName("label_13")
        self.gridLayout_2.addWidget(self.label_13, 0, 4, 1, 1)
        self.dc_total_work_day = QtWidgets.QLineEdit(self.groupBox_2)
        self.dc_total_work_day.setObjectName("dc_total_work_day")
        self.gridLayout_2.addWidget(self.dc_total_work_day, 3, 5, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.groupBox_2)
        self.label_15.setObjectName("label_15")
        self.gridLayout_2.addWidget(self.label_15, 1, 2, 1, 1)
        self.label_27 = QtWidgets.QLabel(self.groupBox_2)
        self.label_27.setObjectName("label_27")
        self.gridLayout_2.addWidget(self.label_27, 5, 2, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.groupBox_2)
        self.label_11.setObjectName("label_11")
        self.gridLayout_2.addWidget(self.label_11, 0, 0, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.groupBox_2)
        self.label_14.setObjectName("label_14")
        self.gridLayout_2.addWidget(self.label_14, 1, 0, 1, 1)
        self.label_24 = QtWidgets.QLabel(self.groupBox_2)
        self.label_24.setObjectName("label_24")
        self.gridLayout_2.addWidget(self.label_24, 4, 2, 1, 1)
        self.dc_charge_curr = QtWidgets.QLineEdit(self.groupBox_2)
        self.dc_charge_curr.setObjectName("dc_charge_curr")
        self.gridLayout_2.addWidget(self.dc_charge_curr, 0, 3, 1, 1)
        self.dc_total_genera = QtWidgets.QLineEdit(self.groupBox_2)
        self.dc_total_genera.setObjectName("dc_total_genera")
        self.gridLayout_2.addWidget(self.dc_total_genera, 4, 5, 1, 1)
        self.label_19 = QtWidgets.QLabel(self.groupBox_2)
        self.label_19.setObjectName("label_19")
        self.gridLayout_2.addWidget(self.label_19, 2, 4, 1, 1)
        self.label_21 = QtWidgets.QLabel(self.groupBox_2)
        self.label_21.setObjectName("label_21")
        self.gridLayout_2.addWidget(self.label_21, 3, 2, 1, 1)
        self.label_26 = QtWidgets.QLabel(self.groupBox_2)
        self.label_26.setObjectName("label_26")
        self.gridLayout_2.addWidget(self.label_26, 5, 0, 1, 1)
        self.dc_bat_overchg_times = QtWidgets.QLineEdit(self.groupBox_2)
        self.dc_bat_overchg_times.setObjectName("dc_bat_overchg_times")
        self.gridLayout_2.addWidget(self.dc_bat_overchg_times, 4, 1, 1, 1)
        self.label_29 = QtWidgets.QLabel(self.groupBox_2)
        self.label_29.setObjectName("label_29")
        self.gridLayout_2.addWidget(self.label_29, 6, 0, 1, 1)
        self.dc_fail_info = QtWidgets.QLineEdit(self.groupBox_2)
        self.dc_fail_info.setObjectName("dc_fail_info")
        self.gridLayout_2.addWidget(self.dc_fail_info, 6, 1, 1, 5)
        self.horizontalLayout_5.addLayout(self.gridLayout_2)
        self.verticalLayout.addWidget(self.groupBox_2)
        self.verticalLayout.setStretch(0, 1)
        self.verticalLayout.setStretch(1, 2)
        self.horizontalLayout_3.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.groupBox_3 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_3.setObjectName("groupBox_3")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.groupBox_3)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.dc_refresh_port = PushButton(self.groupBox_3)
        self.dc_refresh_port.setObjectName("dc_refresh_port")
        self.gridLayout_3.addWidget(self.dc_refresh_port, 2, 2, 1, 1)
        self.label_31 = QtWidgets.QLabel(self.groupBox_3)
        self.label_31.setObjectName("label_31")
        self.gridLayout_3.addWidget(self.label_31, 1, 0, 1, 1)
        self.dc_port_list = ComboBox(self.groupBox_3)
        self.dc_port_list.setObjectName("dc_port_list")
        self.gridLayout_3.addWidget(self.dc_port_list, 1, 1, 1, 1)
        self.dc_login = PushButton(self.groupBox_3)
        self.dc_login.setStyleSheet("PushButton, ToolButton, ToggleButton, ToggleToolButton {\n"
"    color: black;\n"
"    background: rgba(255, 255, 255, 0.7);\n"
"    border: 1px solid rgba(0, 0, 0, 0.073);\n"
"    border-bottom: 1px solid rgba(0, 0, 0, 0.183);\n"
"    border-radius: 5px;\n"
"    /* font: 14px \'HarmonyOS Sans SC\'; */\n"
"    padding: 5px 12px 6px 12px;\n"
"    outline: none;\n"
"}\n"
"\n"
"ToolButton {\n"
"    padding: 5px 9px 6px 8px;\n"
"}\n"
"\n"
"PushButton[hasIcon=false] {\n"
"    padding: 5px 12px 6px 12px;\n"
"}\n"
"\n"
"PushButton[hasIcon=true] {\n"
"    padding: 5px 12px 6px 36px;\n"
"}\n"
"\n"
"DropDownToolButton, PrimaryDropDownToolButton {\n"
"    padding: 5px 31px 6px 8px;\n"
"}\n"
"\n"
"DropDownPushButton[hasIcon=false],\n"
"PrimaryDropDownPushButton[hasIcon=false] {\n"
"    padding: 5px 31px 6px 12px;\n"
"}\n"
"\n"
"DropDownPushButton[hasIcon=true],\n"
"PrimaryDropDownPushButton[hasIcon=true] {\n"
"    padding: 5px 31px 6px 36px;\n"
"}\n"
"\n"
"PushButton:hover, ToolButton:hover, ToggleButton:hover, ToggleToolButton:hover {\n"
"    background: rgba(249, 249, 249, 0.5);\n"
"}\n"
"\n"
"PushButton:pressed, ToolButton:pressed, ToggleButton:pressed, ToggleToolButton:pressed {\n"
"    color: rgba(0, 0, 0, 0.63);\n"
"    background: rgba(249, 249, 249, 0.3);\n"
"    border-bottom: 1px solid rgba(0, 0, 0, 0.073);\n"
"}\n"
"\n"
"PushButton:disabled, ToolButton:disabled, ToggleButton:disabled, ToggleToolButton:disabled {\n"
"    color: rgba(0, 0, 0, 0.36);\n"
"    background: rgba(249, 249, 249, 0.3);\n"
"    border: 1px solid rgba(0, 0, 0, 0.06);\n"
"    border-bottom: 1px solid rgba(0, 0, 0, 0.06);\n"
"}\n"
"\n"
"\n"
"PrimaryPushButton,\n"
"PrimaryToolButton,\n"
"ToggleButton:checked,\n"
"ToggleToolButton:checked {\n"
"    color: white;\n"
"    background-color: #009faa;\n"
"    border: 1px solid #00a7b3;\n"
"    border-bottom: 1px solid #007780;\n"
"}\n"
"\n"
"PrimaryPushButton:hover,\n"
"PrimaryToolButton:hover,\n"
"ToggleButton:checked:hover,\n"
"ToggleToolButton:checked:hover {\n"
"    background-color: #00a7b3;\n"
"    border: 1px solid #2daab3;\n"
"    border-bottom: 1px solid #007780;\n"
"}\n"
"\n"
"PrimaryPushButton:pressed,\n"
"PrimaryToolButton:pressed,\n"
"ToggleButton:checked:pressed,\n"
"ToggleToolButton:checked:pressed {\n"
"    color: rgba(255, 255, 255, 0.63);\n"
"    background-color: #3eabb3;\n"
"    border: 1px solid #3eabb3;\n"
"}\n"
"\n"
"PrimaryPushButton:disabled,\n"
"PrimaryToolButton:disabled,\n"
"ToggleButton:checked:disabled,\n"
"ToggleToolButton:checked:disabled {\n"
"    color: rgba(255, 255, 255, 0.9);\n"
"    background-color: rgb(205, 205, 205);\n"
"    border: 1px solid rgb(205, 205, 205);\n"
"}\n"
"\n"
"SplitDropButton,\n"
"PrimarySplitDropButton {\n"
"    border-left: none;\n"
"    border-top-left-radius: 0;\n"
"    border-bottom-left-radius: 0;\n"
"}\n"
"\n"
"#splitPushButton,\n"
"#splitToolButton,\n"
"#primarySplitPushButton,\n"
"#primarySplitToolButton {\n"
"    border-top-right-radius: 0;\n"
"    border-bottom-right-radius: 0;\n"
"}\n"
"\n"
"#splitPushButton:pressed,\n"
"#splitToolButton:pressed,\n"
"SplitDropButton:pressed {\n"
"    border-bottom: 1px solid rgba(0, 0, 0, 0.183);\n"
"}\n"
"\n"
"PrimarySplitDropButton:pressed {\n"
"    border-bottom: 1px solid #007780;\n"
"}\n"
"\n"
"#primarySplitPushButton, #primarySplitToolButton {\n"
"    border-right: 1px solid #3eabb3;\n"
"}\n"
"\n"
"#primarySplitPushButton:pressed, #primarySplitToolButton:pressed {\n"
"    border-bottom: 1px solid #007780;\n"
"}\n"
"\n"
"HyperlinkButton {\n"
"    /* font: 14px \'Segoe UI\', \'Microsoft YaHei\'; */\n"
"    padding: 6px 12px 6px 12px;\n"
"    color: #009faa;\n"
"    border: none;\n"
"    border-radius: 6px;\n"
"    background-color: transparent;\n"
"}\n"
"\n"
"HyperlinkButton[hasIcon=false] {\n"
"    padding: 6px 12px 6px 12px;\n"
"}\n"
"\n"
"HyperlinkButton[hasIcon=true] {\n"
"    padding: 6px 12px 6px 36px;\n"
"}\n"
"\n"
"HyperlinkButton:hover {\n"
"    color: #009faa;\n"
"    background-color: rgba(0, 0, 0, 10);\n"
"    border: none;\n"
"}\n"
"\n"
"HyperlinkButton:pressed {\n"
"    color: #009faa;\n"
"    background-color: rgba(0, 0, 0, 6);\n"
"    border: none;\n"
"}\n"
"\n"
"HyperlinkButton:disabled {\n"
"    color: rgba(0, 0, 0, 0.43);\n"
"    background-color: transparent;\n"
"    border: none;\n"
"}\n"
"\n"
"\n"
"RadioButton {\n"
"    min-height: 24px;\n"
"    max-height: 24px;\n"
"    background-color: transparent;\n"
"    font: 14px \'Segoe UI\', \'Microsoft YaHei\', \'PingFang SC\';\n"
"    color: black;\n"
"}\n"
"\n"
"RadioButton::indicator {\n"
"    width: 18px;\n"
"    height: 18px;\n"
"    border-radius: 11px;\n"
"    border: 2px solid #999999;\n"
"    background-color: rgba(0, 0, 0, 5);\n"
"    margin-right: 4px;\n"
"}\n"
"\n"
"RadioButton::indicator:hover {\n"
"    background-color: rgba(0, 0, 0, 0);\n"
"}\n"
"\n"
"RadioButton::indicator:pressed {\n"
"    border: 2px solid #bbbbbb;\n"
"    background-color: qradialgradient(spread:pad, cx:0.5, cy:0.5, radius:0.5, fx:0.5, fy:0.5,\n"
"            stop:0 rgb(255, 255, 255),\n"
"            stop:0.5 rgb(255, 255, 255),\n"
"            stop:0.6 rgb(225, 224, 223),\n"
"            stop:1 rgb(225, 224, 223));\n"
"}\n"
"\n"
"RadioButton::indicator:checked {\n"
"    height: 22px;\n"
"    width: 22px;\n"
"    border: none;\n"
"    border-radius: 11px;\n"
"    background-color: qradialgradient(spread:pad, cx:0.5, cy:0.5, radius:0.5, fx:0.5, fy:0.5,\n"
"            stop:0 rgb(255, 255, 255),\n"
"            stop:0.5 rgb(255, 255, 255),\n"
"            stop:0.6 #009faa,\n"
"            stop:1 #009faa);\n"
"}\n"
"\n"
"RadioButton::indicator:checked:hover {\n"
"    background-color: qradialgradient(spread:pad, cx:0.5, cy:0.5, radius:0.5, fx:0.5, fy:0.5,\n"
"            stop:0 rgb(255, 255, 255),\n"
"            stop:0.6 rgb(255, 255, 255),\n"
"            stop:0.7 #009faa,\n"
"            stop:1 #009faa);\n"
"}\n"
"\n"
"RadioButton::indicator:checked:pressed {\n"
"    background-color: qradialgradient(spread:pad, cx:0.5, cy:0.5, radius:0.5, fx:0.5, fy:0.5,\n"
"            stop:0 rgb(255, 255, 255),\n"
"            stop:0.5 rgb(255, 255, 255),\n"
"            stop:0.6 #009faa,\n"
"            stop:1 #009faa);\n"
"}\n"
"\n"
"RadioButton:disabled {\n"
"    color: rgba(0, 0, 0, 110);\n"
"}\n"
"\n"
"RadioButton::indicator:disabled {\n"
"    border: 2px solid #bbbbbb;\n"
"    background-color: transparent;\n"
"}\n"
"\n"
"RadioButton::indicator:disabled:checked {\n"
"    border: none;\n"
"    background-color: qradialgradient(spread:pad, cx:0.5, cy:0.5, radius:0.5, fx:0.5, fy:0.5,\n"
"            stop:0 rgb(255, 255, 255),\n"
"            stop:0.5 rgb(255, 255, 255),\n"
"            stop:0.6 rgba(0, 0, 0, 0.2169),\n"
"            stop:1 rgba(0, 0, 0, 0.2169));\n"
"}\n"
"\n"
"TransparentToolButton,\n"
"TransparentToggleToolButton,\n"
"TransparentDropDownToolButton,\n"
"TransparentPushButton,\n"
"TransparentDropDownPushButton,\n"
"TransparentTogglePushButton {\n"
"    background-color: transparent;\n"
"    border: none;\n"
"    border-radius: 5px;\n"
"    margin: 0;\n"
"}\n"
"\n"
"TransparentToolButton:hover,\n"
"TransparentToggleToolButton:hover,\n"
"TransparentDropDownToolButton:hover,\n"
"TransparentPushButton:hover,\n"
"TransparentDropDownPushButton:hover,\n"
"TransparentTogglePushButton:hover {\n"
"    background-color: rgba(0, 0, 0, 9);\n"
"    border: none;\n"
"}\n"
"\n"
"TransparentToolButton:pressed,\n"
"TransparentToggleToolButton:pressed,\n"
"TransparentDropDownToolButton:pressed,\n"
"TransparentPushButton:pressed,\n"
"TransparentDropDownPushButton:pressed,\n"
"TransparentTogglePushButton:pressed {\n"
"    background-color: rgba(0, 0, 0, 6);\n"
"    border: none;\n"
"}\n"
"\n"
"TransparentToolButton:disabled,\n"
"TransparentToggleToolButton:disabled,\n"
"TransparentDropDownToolButton:disabled,\n"
"TransprentPushButton:disabled,\n"
"TransparentDropDownPushButton:disabled,\n"
"TransprentTogglePushButton:disabled {\n"
"    background-color: transparent;\n"
"    border: none;\n"
"}\n"
"\n"
"\n"
"PillPushButton,\n"
"PillPushButton:hover,\n"
"PillPushButton:pressed,\n"
"PillPushButton:disabled,\n"
"PillPushButton:checked,\n"
"PillPushButton:checked:hover,\n"
"PillPushButton:checked:pressed,\n"
"PillPushButton:disabled:checked,\n"
"PillToolButton,\n"
"PillToolButton:hover,\n"
"PillToolButton:pressed,\n"
"PillToolButton:disabled,\n"
"PillToolButton:checked,\n"
"PillToolButton:checked:hover,\n"
"PillToolButton:checked:pressed,\n"
"PillToolButton:disabled:checked {\n"
"    background-color: transparent;\n"
"    border: none;\n"
"}\n"
"")
        self.dc_login.setObjectName("dc_login")
        self.gridLayout_3.addWidget(self.dc_login, 0, 2, 1, 1)
        self.dc_open_monitor = PushButton(self.groupBox_3)
        self.dc_open_monitor.setObjectName("dc_open_monitor")
        self.gridLayout_3.addWidget(self.dc_open_monitor, 3, 2, 1, 1)
        self.label_32 = QtWidgets.QLabel(self.groupBox_3)
        self.label_32.setObjectName("label_32")
        self.gridLayout_3.addWidget(self.label_32, 3, 0, 1, 1)
        self.label_30 = QtWidgets.QLabel(self.groupBox_3)
        self.label_30.setObjectName("label_30")
        self.gridLayout_3.addWidget(self.label_30, 0, 0, 1, 1)
        self.dc_open_port = PushButton(self.groupBox_3)
        self.dc_open_port.setObjectName("dc_open_port")
        self.gridLayout_3.addWidget(self.dc_open_port, 1, 2, 1, 1)
        self.dc_baud_list = ComboBox(self.groupBox_3)
        self.dc_baud_list.setObjectName("dc_baud_list")
        self.gridLayout_3.addWidget(self.dc_baud_list, 3, 1, 1, 1)
        self.dc_export_monitor = PushButton(self.groupBox_3)
        self.dc_export_monitor.setObjectName("dc_export_monitor")
        self.gridLayout_3.addWidget(self.dc_export_monitor, 4, 2, 1, 1)
        self.PasswordLineEdit = PasswordLineEdit(self.groupBox_3)
        self.PasswordLineEdit.setObjectName("PasswordLineEdit")
        self.gridLayout_3.addWidget(self.PasswordLineEdit, 0, 1, 1, 1)
        self.horizontalLayout_6.addLayout(self.gridLayout_3)
        self.verticalLayout_2.addWidget(self.groupBox_3)
        self.groupBox_4 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_4.setObjectName("groupBox_4")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.groupBox_4)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_37 = QtWidgets.QLabel(self.groupBox_4)
        self.label_37.setObjectName("label_37")
        self.gridLayout_4.addWidget(self.label_37, 1, 2, 1, 1)
        self.label_35 = QtWidgets.QLabel(self.groupBox_4)
        self.label_35.setObjectName("label_35")
        self.gridLayout_4.addWidget(self.label_35, 1, 0, 1, 1)
        self.label_36 = QtWidgets.QLabel(self.groupBox_4)
        self.label_36.setObjectName("label_36")
        self.gridLayout_4.addWidget(self.label_36, 2, 0, 1, 1)
        self.label_38 = QtWidgets.QLabel(self.groupBox_4)
        self.label_38.setObjectName("label_38")
        self.gridLayout_4.addWidget(self.label_38, 2, 2, 1, 1)
        self.label_34 = QtWidgets.QLabel(self.groupBox_4)
        self.label_34.setObjectName("label_34")
        self.gridLayout_4.addWidget(self.label_34, 0, 2, 1, 1)
        self.label_33 = QtWidgets.QLabel(self.groupBox_4)
        self.label_33.setObjectName("label_33")
        self.gridLayout_4.addWidget(self.label_33, 0, 0, 1, 1)
        self.dc_onoff_power = PushButton(self.groupBox_4)
        self.dc_onoff_power.setObjectName("dc_onoff_power")
        self.gridLayout_4.addWidget(self.dc_onoff_power, 0, 1, 1, 1)
        self.dc_reset = PushButton(self.groupBox_4)
        self.dc_reset.setObjectName("dc_reset")
        self.gridLayout_4.addWidget(self.dc_reset, 0, 3, 1, 1)
        self.dc_factory_setting = PushButton(self.groupBox_4)
        self.dc_factory_setting.setObjectName("dc_factory_setting")
        self.gridLayout_4.addWidget(self.dc_factory_setting, 1, 1, 1, 1)
        self.dc_clear_alarm = PushButton(self.groupBox_4)
        self.dc_clear_alarm.setObjectName("dc_clear_alarm")
        self.gridLayout_4.addWidget(self.dc_clear_alarm, 1, 3, 1, 1)
        self.dc_clear_statistic = PushButton(self.groupBox_4)
        self.dc_clear_statistic.setObjectName("dc_clear_statistic")
        self.gridLayout_4.addWidget(self.dc_clear_statistic, 2, 1, 1, 1)
        self.dc_clear_his = PushButton(self.groupBox_4)
        self.dc_clear_his.setObjectName("dc_clear_his")
        self.gridLayout_4.addWidget(self.dc_clear_his, 2, 3, 1, 1)
        self.horizontalLayout_7.addLayout(self.gridLayout_4)
        self.verticalLayout_2.addWidget(self.groupBox_4)
        self.horizontalLayout_3.addLayout(self.verticalLayout_2)
        self.horizontalLayout_3.setStretch(0, 2)
        self.horizontalLayout_3.setStretch(1, 1)
        self.horizontalLayout_2.addLayout(self.horizontalLayout_3)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.tab_2)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.gridLayout_5 = QtWidgets.QGridLayout()
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.label_55 = QtWidgets.QLabel(self.tab_2)
        self.label_55.setObjectName("label_55")
        self.gridLayout_5.addWidget(self.label_55, 5, 5, 1, 1)
        self.label_45 = QtWidgets.QLabel(self.tab_2)
        self.label_45.setObjectName("label_45")
        self.gridLayout_5.addWidget(self.label_45, 2, 1, 1, 1)
        self.label_43 = QtWidgets.QLabel(self.tab_2)
        self.label_43.setObjectName("label_43")
        self.gridLayout_5.addWidget(self.label_43, 1, 3, 1, 1)
        self.label_54 = QtWidgets.QLabel(self.tab_2)
        self.label_54.setObjectName("label_54")
        self.gridLayout_5.addWidget(self.label_54, 5, 1, 1, 1)
        self.label_47 = QtWidgets.QLabel(self.tab_2)
        self.label_47.setObjectName("label_47")
        self.gridLayout_5.addWidget(self.label_47, 2, 5, 1, 1)
        self.label_39 = QtWidgets.QLabel(self.tab_2)
        self.label_39.setObjectName("label_39")
        self.gridLayout_5.addWidget(self.label_39, 0, 1, 1, 1)
        self.label_40 = QtWidgets.QLabel(self.tab_2)
        self.label_40.setObjectName("label_40")
        self.gridLayout_5.addWidget(self.label_40, 0, 3, 1, 1)
        self.label_53 = QtWidgets.QLabel(self.tab_2)
        self.label_53.setObjectName("label_53")
        self.gridLayout_5.addWidget(self.label_53, 5, 3, 1, 1)
        self.label_56 = QtWidgets.QLabel(self.tab_2)
        self.label_56.setObjectName("label_56")
        self.gridLayout_5.addWidget(self.label_56, 6, 1, 1, 1)
        self.label_57 = QtWidgets.QLabel(self.tab_2)
        self.label_57.setObjectName("label_57")
        self.gridLayout_5.addWidget(self.label_57, 6, 3, 1, 1)
        self.label_51 = QtWidgets.QLabel(self.tab_2)
        self.label_51.setObjectName("label_51")
        self.gridLayout_5.addWidget(self.label_51, 4, 1, 1, 1)
        self.label_48 = QtWidgets.QLabel(self.tab_2)
        self.label_48.setObjectName("label_48")
        self.gridLayout_5.addWidget(self.label_48, 3, 1, 1, 1)
        self.label_44 = QtWidgets.QLabel(self.tab_2)
        self.label_44.setObjectName("label_44")
        self.gridLayout_5.addWidget(self.label_44, 1, 5, 1, 1)
        self.label_52 = QtWidgets.QLabel(self.tab_2)
        self.label_52.setObjectName("label_52")
        self.gridLayout_5.addWidget(self.label_52, 4, 3, 1, 1)
        self.label_50 = QtWidgets.QLabel(self.tab_2)
        self.label_50.setObjectName("label_50")
        self.gridLayout_5.addWidget(self.label_50, 3, 5, 1, 1)
        self.label_58 = QtWidgets.QLabel(self.tab_2)
        self.label_58.setObjectName("label_58")
        self.gridLayout_5.addWidget(self.label_58, 6, 5, 1, 1)
        self.label_41 = QtWidgets.QLabel(self.tab_2)
        self.label_41.setObjectName("label_41")
        self.gridLayout_5.addWidget(self.label_41, 0, 5, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem, 0, 0, 1, 1)
        self.label_42 = QtWidgets.QLabel(self.tab_2)
        self.label_42.setObjectName("label_42")
        self.gridLayout_5.addWidget(self.label_42, 1, 1, 1, 1)
        self.label_46 = QtWidgets.QLabel(self.tab_2)
        self.label_46.setObjectName("label_46")
        self.gridLayout_5.addWidget(self.label_46, 2, 3, 1, 1)
        self.label_49 = QtWidgets.QLabel(self.tab_2)
        self.label_49.setObjectName("label_49")
        self.gridLayout_5.addWidget(self.label_49, 3, 3, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem1, 0, 7, 1, 1)
        self.dc_read_set = PushButton(self.tab_2)
        self.dc_read_set.setObjectName("dc_read_set")
        self.gridLayout_5.addWidget(self.dc_read_set, 7, 2, 1, 1)
        self.dc_write_set = PushButton(self.tab_2)
        self.dc_write_set.setObjectName("dc_write_set")
        self.gridLayout_5.addWidget(self.dc_write_set, 7, 4, 1, 1)
        self.dc_charge_elec_set = DoubleSpinBox(self.tab_2)
        self.dc_charge_elec_set.setMaximum(25.0)
        self.dc_charge_elec_set.setObjectName("dc_charge_elec_set")
        self.gridLayout_5.addWidget(self.dc_charge_elec_set, 0, 2, 1, 1)
        self.dc_set_battery_cap = SpinBox(self.tab_2)
        self.dc_set_battery_cap.setObjectName("dc_set_battery_cap")
        self.gridLayout_5.addWidget(self.dc_set_battery_cap, 0, 4, 1, 1)
        self.dc_set_sys_current = SpinBox(self.tab_2)
        self.dc_set_sys_current.setObjectName("dc_set_sys_current")
        self.gridLayout_5.addWidget(self.dc_set_sys_current, 0, 6, 1, 1)
        self.dc_set_battery_type = ComboBox(self.tab_2)
        self.dc_set_battery_type.setText("")
        self.dc_set_battery_type.setObjectName("dc_set_battery_type")
        self.gridLayout_5.addWidget(self.dc_set_battery_type, 1, 2, 1, 1)
        self.dc_set_battery_overpressure = DoubleSpinBox(self.tab_2)
        self.dc_set_battery_overpressure.setDecimals(1)
        self.dc_set_battery_overpressure.setObjectName("dc_set_battery_overpressure")
        self.gridLayout_5.addWidget(self.dc_set_battery_overpressure, 1, 4, 1, 1)
        self.dc_set_charge_limit = DoubleSpinBox(self.tab_2)
        self.dc_set_charge_limit.setDecimals(1)
        self.dc_set_charge_limit.setObjectName("dc_set_charge_limit")
        self.gridLayout_5.addWidget(self.dc_set_charge_limit, 1, 6, 1, 1)
        self.dc_set_even_current = DoubleSpinBox(self.tab_2)
        self.dc_set_even_current.setDecimals(1)
        self.dc_set_even_current.setObjectName("dc_set_even_current")
        self.gridLayout_5.addWidget(self.dc_set_even_current, 2, 2, 1, 1)
        self.dc_set_promote_current = DoubleSpinBox(self.tab_2)
        self.dc_set_promote_current.setDecimals(1)
        self.dc_set_promote_current.setObjectName("dc_set_promote_current")
        self.gridLayout_5.addWidget(self.dc_set_promote_current, 2, 4, 1, 1)
        self.dc_set_float_current = DoubleSpinBox(self.tab_2)
        self.dc_set_float_current.setDecimals(1)
        self.dc_set_float_current.setObjectName("dc_set_float_current")
        self.gridLayout_5.addWidget(self.dc_set_float_current, 2, 6, 1, 1)
        self.dc_set_promote_current_retrun = DoubleSpinBox(self.tab_2)
        self.dc_set_promote_current_retrun.setDecimals(1)
        self.dc_set_promote_current_retrun.setObjectName("dc_set_promote_current_retrun")
        self.gridLayout_5.addWidget(self.dc_set_promote_current_retrun, 3, 2, 1, 1)
        self.dc_BatUnderVolt = DoubleSpinBox(self.tab_2)
        self.dc_BatUnderVolt.setDecimals(1)
        self.dc_BatUnderVolt.setObjectName("dc_BatUnderVolt")
        self.gridLayout_5.addWidget(self.dc_BatUnderVolt, 3, 4, 1, 1)
        self.dc_BatConstChgTime = SpinBox(self.tab_2)
        self.dc_BatConstChgTime.setObjectName("dc_BatConstChgTime")
        self.gridLayout_5.addWidget(self.dc_BatConstChgTime, 3, 6, 1, 1)
        self.dc_BatImprovChgTime = SpinBox(self.tab_2)
        self.dc_BatImprovChgTime.setObjectName("dc_BatImprovChgTime")
        self.gridLayout_5.addWidget(self.dc_BatImprovChgTime, 4, 2, 1, 1)
        self.dc_BatConstChgGapTime = SpinBox(self.tab_2)
        self.dc_BatConstChgGapTime.setObjectName("dc_BatConstChgGapTime")
        self.gridLayout_5.addWidget(self.dc_BatConstChgGapTime, 4, 4, 1, 1)
        self.dc_ChgMode = ComboBox(self.tab_2)
        self.dc_ChgMode.setObjectName("dc_ChgMode")
        self.gridLayout_5.addWidget(self.dc_ChgMode, 5, 2, 1, 1)
        self.dc_ChgModeInMaxWorkVolt = DoubleSpinBox(self.tab_2)
        self.dc_ChgModeInMaxWorkVolt.setDecimals(1)
        self.dc_ChgModeInMaxWorkVolt.setObjectName("dc_ChgModeInMaxWorkVolt")
        self.gridLayout_5.addWidget(self.dc_ChgModeInMaxWorkVolt, 5, 4, 1, 1)
        self.dc_ChgModeInLowWorkVolt = DoubleSpinBox(self.tab_2)
        self.dc_ChgModeInLowWorkVolt.setDecimals(1)
        self.dc_ChgModeInLowWorkVolt.setObjectName("dc_ChgModeInLowWorkVolt")
        self.gridLayout_5.addWidget(self.dc_ChgModeInLowWorkVolt, 5, 6, 1, 1)
        self.dc_CvModeOutVolt = DoubleSpinBox(self.tab_2)
        self.dc_CvModeOutVolt.setDecimals(1)
        self.dc_CvModeOutVolt.setObjectName("dc_CvModeOutVolt")
        self.gridLayout_5.addWidget(self.dc_CvModeOutVolt, 6, 2, 1, 1)
        self.dc_CvModeInMaxWorkVolt = DoubleSpinBox(self.tab_2)
        self.dc_CvModeInMaxWorkVolt.setDecimals(1)
        self.dc_CvModeInMaxWorkVolt.setObjectName("dc_CvModeInMaxWorkVolt")
        self.gridLayout_5.addWidget(self.dc_CvModeInMaxWorkVolt, 6, 4, 1, 1)
        self.dc_CVModeInLowWorkVolt = DoubleSpinBox(self.tab_2)
        self.dc_CVModeInLowWorkVolt.setDecimals(1)
        self.dc_CVModeInLowWorkVolt.setObjectName("dc_CVModeInLowWorkVolt")
        self.gridLayout_5.addWidget(self.dc_CVModeInLowWorkVolt, 6, 6, 1, 1)
        self.gridLayout_5.setColumnStretch(0, 1)
        self.gridLayout_5.setColumnStretch(1, 1)
        self.gridLayout_5.setColumnStretch(2, 2)
        self.gridLayout_5.setColumnStretch(3, 1)
        self.gridLayout_5.setColumnStretch(4, 2)
        self.gridLayout_5.setColumnStretch(5, 1)
        self.gridLayout_5.setColumnStretch(6, 2)
        self.gridLayout_5.setColumnStretch(7, 1)
        self.horizontalLayout_8.addLayout(self.gridLayout_5)
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.tab_3)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.dc_clear_table = PushButton(self.tab_3)
        self.dc_clear_table.setObjectName("dc_clear_table")
        self.verticalLayout_3.addWidget(self.dc_clear_table)
        self.dc_tableWidget = QtWidgets.QTableWidget(self.tab_3)
        self.dc_tableWidget.setObjectName("dc_tableWidget")
        self.dc_tableWidget.setColumnCount(3)
        self.dc_tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.dc_tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.dc_tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.dc_tableWidget.setHorizontalHeaderItem(2, item)
        self.verticalLayout_3.addWidget(self.dc_tableWidget)
        self.horizontalLayout_9.addLayout(self.verticalLayout_3)
        self.tabWidget.addTab(self.tab_3, "")
        self.horizontalLayout.addWidget(self.tabWidget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1181, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "DC-DC 充电器"))
        self.groupBox.setTitle(_translate("MainWindow", "产品信息"))
        self.label_5.setText(_translate("MainWindow", "软件版本"))
        self.label_3.setText(_translate("MainWindow", "产品类型"))
        self.label_2.setText(_translate("MainWindow", "额定充电电流"))
        self.label_10.setText(_translate("MainWindow", "设备名字"))
        self.label_6.setText(_translate("MainWindow", "硬件版本"))
        self.label_4.setText(_translate("MainWindow", "产品规格"))
        self.label_9.setText(_translate("MainWindow", "CAN程序版本"))
        self.label.setText(_translate("MainWindow", "系统电压"))
        self.label_8.setText(_translate("MainWindow", "设备地址"))
        self.label_7.setText(_translate("MainWindow", "产品序列号"))
        self.groupBox_2.setTitle(_translate("MainWindow", "控制器信息"))
        self.label_16.setText(_translate("MainWindow", "充电功率"))
        self.label_23.setText(_translate("MainWindow", "蓄电池总充满次数"))
        self.label_28.setText(_translate("MainWindow", "散热器"))
        self.label_18.setText(_translate("MainWindow", "开机以来最高电压"))
        self.label_17.setText(_translate("MainWindow", "开机以来最低电压"))
        self.label_12.setText(_translate("MainWindow", "充电电流"))
        self.label_25.setText(_translate("MainWindow", "累计发电量"))
        self.label_20.setText(_translate("MainWindow", "当天充电安时数"))
        self.label_22.setText(_translate("MainWindow", "总运行天数"))
        self.label_13.setText(_translate("MainWindow", "设备温度"))
        self.label_15.setText(_translate("MainWindow", "输入电压"))
        self.label_27.setText(_translate("MainWindow", "Mos管温度"))
        self.label_11.setText(_translate("MainWindow", "蓄电池电压"))
        self.label_14.setText(_translate("MainWindow", "蓄电池温度"))
        self.label_24.setText(_translate("MainWindow", "蓄电池总充电安时数"))
        self.label_19.setText(_translate("MainWindow", "开机以来充电最大电流"))
        self.label_21.setText(_translate("MainWindow", "当天发电量"))
        self.label_26.setText(_translate("MainWindow", "充电状态"))
        self.label_29.setText(_translate("MainWindow", "控制器故障/告警信息"))
        self.groupBox_3.setTitle(_translate("MainWindow", "操作台"))
        self.dc_refresh_port.setText(_translate("MainWindow", "刷新串口"))
        self.label_31.setText(_translate("MainWindow", "串口号"))
        self.dc_login.setText(_translate("MainWindow", "登录"))
        self.dc_open_monitor.setText(_translate("MainWindow", "开启监控"))
        self.label_32.setText(_translate("MainWindow", "波特率(bps)"))
        self.label_30.setText(_translate("MainWindow", "管理员密码"))
        self.dc_open_port.setText(_translate("MainWindow", "打开串口"))
        self.dc_export_monitor.setText(_translate("MainWindow", "导出监控数据"))
        self.groupBox_4.setTitle(_translate("MainWindow", "设备控制"))
        self.label_37.setText(_translate("MainWindow", "清除当前告警"))
        self.label_35.setText(_translate("MainWindow", "恢复出厂"))
        self.label_36.setText(_translate("MainWindow", "清除统计量"))
        self.label_38.setText(_translate("MainWindow", "清除历史记录"))
        self.label_34.setText(_translate("MainWindow", "复位"))
        self.label_33.setText(_translate("MainWindow", "开关机"))
        self.dc_onoff_power.setText(_translate("MainWindow", "开机"))
        self.dc_reset.setText(_translate("MainWindow", "发送"))
        self.dc_factory_setting.setText(_translate("MainWindow", "发送"))
        self.dc_clear_alarm.setText(_translate("MainWindow", "发送"))
        self.dc_clear_statistic.setText(_translate("MainWindow", "发送"))
        self.dc_clear_his.setText(_translate("MainWindow", "发送"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "实时监控"))
        self.label_55.setText(_translate("MainWindow", "充电模式低于此电压停冲"))
        self.label_45.setText(_translate("MainWindow", "均衡充电电压"))
        self.label_43.setText(_translate("MainWindow", "超压电压"))
        self.label_54.setText(_translate("MainWindow", "充电模式"))
        self.label_47.setText(_translate("MainWindow", "浮充充电电压"))
        self.label_39.setText(_translate("MainWindow", "充电电流设置"))
        self.label_40.setText(_translate("MainWindow", "蓄电池标称容量"))
        self.label_53.setText(_translate("MainWindow", "充电模式高于此电压充电"))
        self.label_56.setText(_translate("MainWindow", "电源模式的输出电压"))
        self.label_57.setText(_translate("MainWindow", "电源模式高于此电压充电"))
        self.label_51.setText(_translate("MainWindow", "提升充电时间"))
        self.label_48.setText(_translate("MainWindow", "提升充电返回电压"))
        self.label_44.setText(_translate("MainWindow", "充电限制电压"))
        self.label_52.setText(_translate("MainWindow", "均衡充电间隔"))
        self.label_50.setText(_translate("MainWindow", "均衡充电时间"))
        self.label_58.setText(_translate("MainWindow", "电源模式低于此电压停冲"))
        self.label_41.setText(_translate("MainWindow", "系统电压设置"))
        self.label_42.setText(_translate("MainWindow", "蓄电池类型"))
        self.label_46.setText(_translate("MainWindow", "提升充电电压"))
        self.label_49.setText(_translate("MainWindow", "欠压警告电压"))
        self.dc_read_set.setText(_translate("MainWindow", "读取数据"))
        self.dc_write_set.setText(_translate("MainWindow", "写入数据"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "参数设置"))
        self.dc_clear_table.setText(_translate("MainWindow", "清空内容"))
        item = self.dc_tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Time"))
        item = self.dc_tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Direction"))
        item = self.dc_tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Send/Receive Data(Hex)"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "串口数据"))
from qfluentwidgets import ComboBox, DoubleSpinBox, PasswordLineEdit, PushButton, SpinBox
