# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'E:\xy\xy\project\AC_charger\ui\main_meun.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(300, 400)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(9, 9, 281, 71))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setStyleSheet("font: 16pt \"微软雅黑\";")
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 1, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 0, 2, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 0, 0, 1, 1)
        self.InverterButton = QtWidgets.QPushButton(self.centralwidget)
        self.InverterButton.setGeometry(QtCore.QRect(70, 248, 161, 50))
        self.InverterButton.setMinimumSize(QtCore.QSize(0, 50))
        self.InverterButton.setStyleSheet("font: 9pt \"微软雅黑\";")
        self.InverterButton.setObjectName("InverterButton")
        self.acchargeButton = QtWidgets.QPushButton(self.centralwidget)
        self.acchargeButton.setGeometry(QtCore.QRect(70, 112, 161, 50))
        self.acchargeButton.setMinimumSize(QtCore.QSize(0, 50))
        self.acchargeButton.setStyleSheet("font: 9pt \"微软雅黑\";")
        self.acchargeButton.setObjectName("acchargeButton")
        self.bmsButton = QtWidgets.QPushButton(self.centralwidget)
        self.bmsButton.setGeometry(QtCore.QRect(70, 180, 161, 50))
        self.bmsButton.setMinimumSize(QtCore.QSize(0, 50))
        self.bmsButton.setStyleSheet("font: 9pt \"微软雅黑\";")
        self.bmsButton.setObjectName("bmsButton")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 300, 22))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.lang_zh = QtWidgets.QAction(MainWindow)
        self.lang_zh.setObjectName("lang_zh")
        self.lang_en = QtWidgets.QAction(MainWindow)
        self.lang_en.setObjectName("lang_en")
        self.menu.addAction(self.lang_zh)
        self.menu.addAction(self.lang_en)
        self.menubar.addAction(self.menu.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "主菜单"))
        self.label.setText(_translate("MainWindow", "选择连接的设备"))
        self.InverterButton.setText(_translate("MainWindow", "逆变器"))
        self.acchargeButton.setText(_translate("MainWindow", "AC/DC 充电器"))
        self.bmsButton.setText(_translate("MainWindow", "BMS 电池管理器"))
        self.menu.setTitle(_translate("MainWindow", "语言"))
        self.lang_zh.setText(_translate("MainWindow", "中文"))
        self.lang_en.setText(_translate("MainWindow", "English"))
