# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'E:\svn\SrneUpperComputer\ui\main_meun.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1000, 689)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/硕日logo.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setAutoFillBackground(False)
        MainWindow.setStyleSheet("")
        MainWindow.setIconSize(QtCore.QSize(111, 32))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.InverterButton = QtWidgets.QPushButton(self.centralwidget)
        self.InverterButton.setGeometry(QtCore.QRect(664, 234, 200, 251))
        self.InverterButton.setMinimumSize(QtCore.QSize(0, 50))
        self.InverterButton.setStyleSheet("background: transparent;")
        self.InverterButton.setText("")
        self.InverterButton.setObjectName("InverterButton")
        self.acchargeButton = QtWidgets.QPushButton(self.centralwidget)
        self.acchargeButton.setGeometry(QtCore.QRect(135, 233, 200, 250))
        self.acchargeButton.setMinimumSize(QtCore.QSize(0, 50))
        self.acchargeButton.setStyleSheet("background: transparent;")
        self.acchargeButton.setText("")
        self.acchargeButton.setObjectName("acchargeButton")
        self.bmsButton = QtWidgets.QPushButton(self.centralwidget)
        self.bmsButton.setGeometry(QtCore.QRect(401, 233, 200, 251))
        self.bmsButton.setMinimumSize(QtCore.QSize(0, 50))
        self.bmsButton.setStyleSheet("background: transparent;")
        self.bmsButton.setText("")
        self.bmsButton.setObjectName("bmsButton")
        self.listView = QtWidgets.QListView(self.centralwidget)
        self.listView.setGeometry(QtCore.QRect(0, 0, 1000, 689))
        self.listView.setStyleSheet("background-image:url(:/背景.png)")
        self.listView.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.listView.setObjectName("listView")
        self.listView_2 = QtWidgets.QListView(self.centralwidget)
        self.listView_2.setGeometry(QtCore.QRect(55, 134, 891, 436))
        self.listView_2.setStyleSheet("background-image:url(:/选择连接设备框.png)")
        self.listView_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.listView_2.setObjectName("listView_2")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(390, 111, 231, 61))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(-1)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setStyleSheet("background: transparent;\n"
"font-size: 32px;\n"
"font-family: \"微软雅黑\";\n"
"color:#F37C00;")
        self.label.setObjectName("label")
        self.ac_bg = QtWidgets.QListView(self.centralwidget)
        self.ac_bg.setGeometry(QtCore.QRect(136, 237, 200, 244))
        self.ac_bg.setStyleSheet("background-color:#FEFEFE;\n"
"border: 1px solid #E8E8E8;\n"
"")
        self.ac_bg.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.ac_bg.setViewMode(QtWidgets.QListView.ListMode)
        self.ac_bg.setObjectName("ac_bg")
        self.bms_bg = QtWidgets.QListView(self.centralwidget)
        self.bms_bg.setGeometry(QtCore.QRect(400, 237, 200, 244))
        self.bms_bg.setStyleSheet("background-color: #FEFEFE;\n"
"border: 1px solid #E8E8E8;")
        self.bms_bg.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.bms_bg.setObjectName("bms_bg")
        self.inverter_bg = QtWidgets.QListView(self.centralwidget)
        self.inverter_bg.setGeometry(QtCore.QRect(664, 237, 200, 244))
        self.inverter_bg.setStyleSheet("background-color: #FEFEFE;\n"
"border: 1px solid #E8E8E8;")
        self.inverter_bg.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.inverter_bg.setObjectName("inverter_bg")
        self.listView_6 = QtWidgets.QListView(self.centralwidget)
        self.listView_6.setGeometry(QtCore.QRect(208, 277, 55, 113))
        self.listView_6.setStyleSheet("background-image:url(:/AC充电器.png)")
        self.listView_6.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.listView_6.setObjectName("listView_6")
        self.ac_text = QtWidgets.QLabel(self.centralwidget)
        self.ac_text.setGeometry(QtCore.QRect(186, 415, 131, 31))
        self.ac_text.setStyleSheet("color:#8A4600;\n"
"font-size:16pt;\n"
"text-align: center;\n"
"font-family: \"微软雅黑\";")
        self.ac_text.setObjectName("ac_text")
        self.listView_7 = QtWidgets.QListView(self.centralwidget)
        self.listView_7.setGeometry(QtCore.QRect(465, 277, 70, 113))
        self.listView_7.setStyleSheet("background-image:url(:/bms(暂用).png)")
        self.listView_7.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.listView_7.setObjectName("listView_7")
        self.bms_text = QtWidgets.QLabel(self.centralwidget)
        self.bms_text.setGeometry(QtCore.QRect(476, 419, 51, 21))
        self.bms_text.setStyleSheet("color:#8A4600;\n"
"font-size:16pt;\n"
"text-align: center;\n"
"font-family: \"微软雅黑\";")
        self.bms_text.setObjectName("bms_text")
        self.listView_8 = QtWidgets.QListView(self.centralwidget)
        self.listView_8.setGeometry(QtCore.QRect(700, 282, 124, 102))
        self.listView_8.setStyleSheet("background-image:url(:/逆变器.png)")
        self.listView_8.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.listView_8.setObjectName("listView_8")
        self.inverter_text = QtWidgets.QLabel(self.centralwidget)
        self.inverter_text.setGeometry(QtCore.QRect(736, 419, 91, 21))
        self.inverter_text.setStyleSheet("color:#8A4600;\n"
"font-size:16pt;\n"
"text-align: center;\n"
"font-family: \"微软雅黑\";")
        self.inverter_text.setObjectName("inverter_text")
        self.listView.raise_()
        self.listView_2.raise_()
        self.label.raise_()
        self.ac_bg.raise_()
        self.bms_bg.raise_()
        self.inverter_bg.raise_()
        self.listView_6.raise_()
        self.ac_text.raise_()
        self.listView_7.raise_()
        self.bms_text.raise_()
        self.listView_8.raise_()
        self.inverter_text.raise_()
        self.InverterButton.raise_()
        self.acchargeButton.raise_()
        self.bmsButton.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1000, 22))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        MainWindow.setMenuBar(self.menubar)
        self.lang_zh = QtWidgets.QAction(MainWindow)
        self.lang_zh.setObjectName("lang_zh")
        self.lang_en = QtWidgets.QAction(MainWindow)
        self.lang_en.setObjectName("lang_en")
        self.menu.addAction(self.lang_zh)
        self.menu.addAction(self.lang_en)
        self.menubar.addAction(self.menu.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "SRNE"))
        self.label.setText(_translate("MainWindow", "选择连接的设备"))
        self.ac_text.setText(_translate("MainWindow", "AC 充电器"))
        self.bms_text.setText(_translate("MainWindow", "BMS"))
        self.inverter_text.setText(_translate("MainWindow", "逆变器"))
        self.menu.setTitle(_translate("MainWindow", "语言"))
        self.lang_zh.setText(_translate("MainWindow", "中文"))
        self.lang_en.setText(_translate("MainWindow", "English"))
from resources.images import ui
